stages:
  - install
  - test
  - code_quality
  - security
  - build
  - scan
  - deploy

# ------------------ INSTALL ------------------
install_backend:
  stage: install
  script:
    - cd backend
    - npm install
  artifacts:
    paths:
      - backend/node_modules/

install_frontend:
  stage: install
  script:
    - cd frontend
    - npm install
  artifacts:
    paths:
      - frontend/node_modules/

# ------------------ TEST ------------------
run_backend_tests:
  stage: test
  script:
    - cd backend
    - npm test

run_frontend_tests:
  stage: test
  script:
    - cd frontend
    - npm test

# ------------------ CODE QUALITY ------------------
eslint_check:
  stage: code_quality
  script:
    - cd frontend
    - npx eslint .

# ------------------ SECURITY ------------------
snyk_scan:
  stage: security
  script:
    - snyk test --all-projects

# ------------------ BUILD ------------------
build_images:
  stage: build
  script:
    - echo "Building Docker images..."
    - docker-compose build
  artifacts:
    paths:
      - docker_images/
  tags:
    - docker

# ------------------ TRIVY SCAN ------------------
trivy_scan:
  stage: scan
  script:
    - echo "Scanning Docker images with Trivy..."
    - trivy image your_image_name:latest
  needs:
    - build_images
  tags:
    - docker

# ------------------ DEPLOY ------------------
deploy_app:
  stage: deploy
  script:
    - echo "Deploying application using Docker Compose..."
    - docker-compose -f docker-compose.yml -p devsecops_flawless up -d --build
  only:
    - main
  tags:
    - docker
