name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd backend
          npm install

      - name: Run Linter
        run: |
          cd backend
          npx eslint . --ext .js

      - name: Run Tests
        run: |
          cd backend
          npm test
