name: OWASP ZAP Scan

on:
  pull_request:
    branches: [main]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Scan
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:5000'
